# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-16 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0004_document_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='Email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='Name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='document',
            name='Phone',
            field=models.CharField(max_length=30),
        ),
    ]
